* Contributing
  :PROPERTIES:
  :CUSTOM_ID: contributing
  :END:

This is a simple package at the moment.
I imagine it will stay pretty simple and stable, and that enhancements will focus on the =bibtex-actions-read= function.

Otherwise, I expect most innovations to focus on configuration details laid out on the wiki.
You should feel free to add your ideas there.

You can of course write your own functions that rely on =bibtex-actions-read=, but if you want to share it more widely, you should consider submitting it for inclusion in [[https://github.com/tmalsburg/helm-bibtex][bibtex-completion]]. itself.

If you do submit a PR, details:

- Follow the [[https://github.com/bbatsov/emacs-lisp-style-guide][elisp style guide]].
- If the CI flags any errors or warnings, which it will report on the "files" tab, please fix them.
- Just by way of explanation, I use =cl-loop= here rather than =mapcar=, because it's slightly more clear to me, and is [[https://nullprogram.com/blog/2017/01/30/][supposedly faster]].
